// Automatically generated by astro-icon
// 3a70498b9bf2f027ab0144c482027893298e2865d3531a402349c9895733a66a

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "facebook24"
		| "instagram24"
		| "tiktok24"
		| "TriangleLogo";
}