media:
  input: src/media
  output: /media
content:
  - name: "settings"
    label: "Basic Settings"
    type: "file"
    path: "src/data/settings.json"
    fields:
      - { name: "name", label: "Business Name", type: "string", required: true }
      - { name: "email", label: "Email Address", type: "string", required: true }
      - { name: "phone", label: "Phone Number", type: "string", required: true }
      - { name: "address", label: "Address", type: "string", required: true }
      - { name: "title", label: "Title of Wwebsite", type: "string", required: true }
      - { name: "description", label: "Description of Website", type: "string", required: true }
      - { name: "url", label: "URL", type: "string", required: true }
      - { name: "keywords", label: "Keywords", type: "string",}
      - { name: "image", label: "OG:Image", type: "image",}
  - name: "social"
    label: "Social Media"
    type: "file"
    path: "src/data/social.json"
    fields:
      - { name: "facebook", label: "Facebook", type: "string",}
      - { name: "twitter", label: "Twitter", type: "string",}
      - { name: "instagram", label: "Instagram", type: "string",}
      - { name: "linkedin", label: "LinkedIn", type: "string",}
      - { name: "youtube", label: "Youtube", type: "string",}  
  - name: "index"
    label: "Home Page Settings" 
    path: "src/pages/index.astro"
    type: "file"
    fields:
    - { name: "heading", label: "Hero Heading", type: "text",}
    - { name: "subheading", label: "Hero Subheading", type: "text",}
    - { name: "heroImg", label: "Hero Image", type: "image", options: { path: "src/media"},}
    - { name: "aboutText", label: "About Description", type: "text",}
    - { name: "logoCloud", label: "Logo Cloud", type: "image", options: { path: "src/media/logo_cloud"},}
    - { name: "videoCarousel", label: "Video Carousel", type: "image", options: { path: "src/media/video_carousel", multiple: "true", max: "6"},}

    