media:
  input: src/assets
  output: /assets

content:
  - name: "projects"
    label: "Projects"
    type: "collection"
    path: "src/content/projects"
    fields:
      - name: "title"
        label: "Title"
        type: "string"
        required: true 
      - name: "author"
        label: "Author" 
        type: "string" 
        required: true
      - name: "draft"
        label: "Draft"
        type: "boolean" 
      - name: "cover"
        label: "Cover Image"
        type: "image"
        options:
          path: "./projects/assets"
      - name: "video" 
        label: "Video"
        type: "image"
        options:
          path: "/assets"
          extensions: ["mp4"] 
      - name: "description" 
        label: "Description"
        type: "text" 
      - name: "body"
        label: "Content"
        type: "rich-text" 
  - name: "settings"
    label: "Site Settings"
    type: "file"
    path: "src/data/settings.json"
    fields:
      - { name: "title", label: "Website Title", type: "string", required: true }
      - { name: "description", label: "Website Description", type: "text", required: true }
      - { name: "url", label: "Website URL", type: "string", required: true }
      - { name: "name", label: "Business Name", type: "string", required: true }
      - { name: "instagramURL", label: "Instagram URL", type: "string" }
      - { name: "tikTokURL", label: "TikTok URL", type: "string" }
      - { name: "introVideo", label: "Background Video", type: "image", options: { path: "/assets", extensions: ["mp4", "mov", "webm"] } }
      - { name: "logos", label: "Logos", type: "image", list: true, options: { path: "/assets" }}
      - { name: "aboutText", label: "About Your Business", type: "rich-text" }
      - { name: "contentFeed", label: "Content Reel", type: "file", list: true, options: { path: "/assets", extensions: ["mp4", "mov", "webm"] } }


  