media:
  input: src/assets
  output: /assets

content:
  - name: "projects"
    label: "Projects"
    type: "collection"
    path: "src/content/projects"
    fields:
      - name: "title"
        label: "Title"
        type: "string"
        required: true 
      - name: "author"
        label: "Author" 
        type: "string" 
        required: true
      - name: "draft"
        label: "Draft"
        type: "boolean" 
      - name: "cover"
        label: "Cover Image"
        type: "image"
        options:
          path: "./projects/assets"
      - name: "video" 
        label: "Video"
        type: "image"
        options:
          path: "/assets"
          extensions: ["mp4"] 
      - name: "description" 
        label: "Description"
        type: "text" 
      - name: "body"
        label: "Content"
        type: "rich-text" 
  - name: "index"
    label: "Home Page"
    type: "file"
    path: "src/pages/index.astro"
    fields: 
      - name: "seo"
        label: "SEO Settings"
        type: "object"
        fields:
        - name: "title"
          label: "Title"
          type: "string"
        - name: "description"
          label: "Description"
          type: "string"
      - name: "heroVideo"
        label: "Video For Hero Section"
        type: "image"
        options:
          path: "/assets"
          extensions: ["mp4"]
      - name: "mainTitle"
        label: "Main Heading"
        type: "string"
      - name: "subTitle"
        label: "Website Subtitle"
        type: "string"
      - name: "aboutTitle"
        label: "About Section Heading"
        type: "string"
      - name: "aboutText1"
        label: "First About Paragraph"
        type: "text"
      - name: "aboutText2"
        label: "Second About Section Paragraph"
        type: "text"
